### ISSUE TITLE
Todo: form to select colors ?

### ISSUE THREAD

**Issue by Scheigster** [Sloth6/FB-Graffiti#1]
Hello!

I truly appreciate your extension, at last Facebook looks funny :+1: 

I would ask if you'd put in your own todo list a form to choose color from RGB value ? Or maybe a hexadecimal one (probably better in fact) ?

I think it would fit nicely in your js code of the palette ;)

Have fun,
Maël

**Comment by joel-simon** [comment]
Hello Scheigy! Thank you for your comment. 

Regarding your question, I feel as though very few people will pick a color based off a number. That is a very specific thing to do. I want to prioritize the features that will be more widely useful.

Thanks,
Joel
